// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// tryp
SEXP tryp(Rcpp::NumericVector params, Rcpp::IntegerVector init, Rcpp::IntegerVector times, Rcpp::IntegerVector stage1_passive, Rcpp::IntegerVector stage2_passive, Rcpp::IntegerVector seed, Rcpp::IntegerVector verbose);
RcppExport SEXP trypR_tryp(SEXP paramsSEXP, SEXP initSEXP, SEXP timesSEXP, SEXP stage1_passiveSEXP, SEXP stage2_passiveSEXP, SEXP seedSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type init(initSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type times(timesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type stage1_passive(stage1_passiveSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type stage2_passive(stage2_passiveSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type verbose(verboseSEXP);
    __result = Rcpp::wrap(tryp(params, init, times, stage1_passive, stage2_passive, seed, verbose));
    return __result;
END_RCPP
}
