# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tryp <- function(params, init, times, stage1_passive = as.integer( c()), stage2_passive = as.integer( c()), seed = as.integer( c()), verbose = as.integer( c())) {
    .Call('trypR_tryp', PACKAGE = 'trypR', params, init, times, stage1_passive, stage2_passive, seed, verbose)
}

