# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

chronic <- function(init, params, times, stage1_passive = as.integer( c()), stage2_passive = as.integer( c()), seed = NULL, verbose = 0L) {
    .Call('trypR_chronic', PACKAGE = 'trypR', init, params, times, stage1_passive, stage2_passive, seed, verbose)
}

